export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_INSTRUCTIONS_EXPANDED = 'SET_INSTRUCTIONS_EXPANDED';
export const FETCH_DECK_RESULT='FETCH_DECK_RESULT';
export const FETCH_DECK_ERROR = 'FETCH_DECK_ERROR';
export const SET_GUESS ='SET_GUESS';

export const DECK = {
    FETCH_SUCCESS:'DECK_FETCH_SUCCESS',
    FETCH_ERROR: 'DECK_FETCH_ERROR'
};
export const DECK_DRAW = {
    FETCH_SUCCESS: 'DECK_DRAW_FETCH_SUCCESS',
    FETCH_ERROR: 'DECK_DRAW_FETCH_ERROR',
    FETCH_GAME_END :'FETCH_GAME_END'
}